import type { Metadata } from "next";
import { Inter, Caveat } from "next/font/google";
import "./globals.css";
import Header from "@components/Header/Header";
import React from "react";
import Footer from "@components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const caveatMono = Caveat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-caveat-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter} ${caveatMono.variable} flex flex-col justify-between overflow-hidden`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
